### ISSUE TITLE
Provide a "valid constant name" validation mode

### ISSUE THREAD

**Issue by myronmarston** [xaviershay/rspec-fire#16]
I have, on occasion, accidentally done this:

``` ruby
describe MyClass do
  it "does something with a widget" do
    widget = fire_double("Widgt")
    widget.should_receive(:widgify)

    MyClass.do_something(widget)
  end
end
```

I fat-fingered the spelling of the the `Widget` constant, and the fire double in my spec will always be a normal double, with none of the interface-verifying goodness rspec-fire would usually give me, even when run with my entire code base loaded.

It'd be nice if there was a way to have rspec-fire tell me about these issues.  Obviously, when I'm running a one-off spec without the `Widget` class loaded, there's no way for rspec-fire to know it's not a valid constant name.  However, when I run all my specs together (which I generally do as I create each git commit), it'd be nice to have it run the specs with an rspec-fire mode that will cause an error to be raised if a fire double (or fire class double) is given an unloaded constant name.  Essentially this would be a config option that I would set in my `spec_helper` (or `full_spec_helper`, or whatever I call my file that loads the entire environment).

Thoughts?

**Comment by xaviershay** [comment]
My only concern is that would add a lot more code since there currently isn't any sort of configuration in `rspec-fire`, I don't think.
