### ISSUE TITLE
Using rspec-fire with rspec-rails mocks

### ISSUE THREAD

**Issue by fschwahn** [xaviershay/rspec-fire#32]
Hi,
I haven't found any information on it, and I thought it might be interesting to others, so I'm posting it here. When I'm testing a rails application, I usually use `mock_model` if I want to test the interface with associations (mainly to prevent AssociationTypeMismatch exceptions). Is it possible to use rspec-fire with mock_model? Or would I have to stub out the association-method on the class under test? I usually refrain from doing that.

Thanks for this gem!
Fabian

**Comment by xaviershay** [comment]
No support for this. Stubbing association methods is usually an anti-pattern so I probably won't add it.

(If you had a specific example I could explain the above further.)
