### ISSUE TITLE
Mocking active record finders with rspec-fire?

### ISSUE THREAD

**Issue by gsmendoza** [xaviershay/rspec-fire#33]
Hi @xaviershay,

Thanks for the awesome gem! I have a question. The readme says that it's possible to double active record finders by subclassing FireDouble, but I can't figure out how to do this. I appreciate your help. You can find the details at [stackoverflow](http://stackoverflow.com/questions/16848682/how-do-i-mock-active-record-finders-with-rspec-fire). 

Thanks,
George

**Comment by xaviershay** [comment]
Answered over at SO.
