### ISSUE TITLE
Add messaging to help with upgrade to RSpec 3

### ISSUE THREAD

**Issue by myronmarston** [xaviershay/rspec-fire#41]
I'm upgrading a project to RSpec 3 and got this from bundler:

```
Bundler could not find compatible versions for gem "rspec":
  In Gemfile:
    rspec-fire (>= 0) ruby depends on
      rspec (~> 2.11) ruby

    rspec (3.0.0.pre)
```

Solution was to remove rspec-fire from my gemfile now that rspec-mocks has the functionality (and the same API).  However, other users may not realize this and think they can't upgrade to RSpec 3 if they use rspec-fire or that they have to remove their uses of rspec-fire's API.  I think there's a better experience we can provide:
- Release a version of rspec-fire with its rspec version constrained to `'>= 2.11', '< 4'` so that it can be installed on a project using rspec 3.
- Put conditional code in `lib/rspec/fire.rb` that detects the rspec-mocks version, and, if it's `3.x` prints a message telling users they no longer need to use rspec-fire as rspec-mocks now has that functionality built in.
- The conditional should also prevent rspec-fire from overwriting rspec-mocks' versions of the methods.

**Comment by xaviershay** [comment]
On my list.
