### ISSUE TITLE
Methods stubbed in hash are not verified

### ISSUE THREAD

**Issue by bethesque** [xaviershay/rspec-fire#44]
eg.

```

class Bethtest
end

let(:bethtest) { instance_double("Bethtest", :doesnotexist => nil) }
```

does not raise any error.

See failing spec here

https://github.com/bethesque/rspec-fire-test

**Comment by xaviershay** [comment]
Thanks for the report! There was a spec for the positive behaviour of this, but not the negative: https://github.com/xaviershay/rspec-fire/blob/master/spec/fire_double_spec.rb#L178

I verified that your test case works as expected in the latest version `rspec-mocks-3.0.0.beta1` (which completely replaces this gem).

Some unrelated notes about your repro:
- `before { Bethtest.stub ... }` is a no-op and not required.
- Don't include bundler in your `Gemfile`, creates weird cyclic problems with bundler trying to require itself.

**Comment by bethesque** [comment]
Ah yeah, stubbing "new" was left over from my original example, which had an extra class that used Bethtest as a collaborator that I realised later I didn't need.

Never noticed problems with the bundler thing before, it's in all our our Gemfiles. Is it because you have 1.4 installed? Maybe it's because we haven't upgraded yet that it hasn't hit us.

Thanks for the quick turn around!

**Comment by xaviershay** [comment]
yeah I'm on 1.4
