### ISSUE TITLE
Ruby2 keyword args

### ISSUE THREAD

**Issue by suan** [xaviershay/rspec-fire#47]
Are Ruby2 keyword args supported? And if not, any plans to support them?

**Comment by myronmarston** [comment]
rspec-fire has been merged into rspec-mocks for RSpec 3, and the version of rspec-fire's features there have many improvements, including support for keywords args.

See rspec/rspec-mocks#543 for the recently added support for keyword args.

RSpec 3.0.0.beta2 will be out very soon with this feature.
